# Generated by Django 3.1.2 on 2020-11-08 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPointProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_description', models.TextField()),
                ('requirements', multiselectfield.db.fields.MultiSelectField(choices=[('Alignment', 'Check for alignment issues, fix fonts and font sizes'), ('Table conversion', 'Check for alignment issues, fix fonts and font sizes'), ('Cover and divider images', 'Use appropriate cover image and divider image'), ('Icons', 'Use appropriate images and icons/pictograms'), ('Basic animation', 'Add basic animations/transitions'), ('Interactive pdf', 'Convert to an interactive PDF'), ('Themed', 'Develop a theme/style for the document and design the document based on the theme'), ('Infographics', 'Change layouts to high-end infographics by adding vectors/pictograms'), ('Complex animations', 'Use high-end complex animations to represent the data')], max_length=128)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PowerPointQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerpoint', to='quote.powerpointproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
