# Generated by Django 3.1.2 on 2020-11-08 00:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpointproject',
            name='requirements',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Alignment', 'Check for alignment issues, fix fonts and font sizes'), ('Table conversion', 'Change text/table to other layouts to represent better'), ('Cover and divider images', 'Use appropriate cover image and divider image'), ('Icons', 'Use appropriate images and icons/pictograms'), ('Basic animation', 'Add basic animations/transitions'), ('Interactive pdf', 'Convert to an interactive PDF'), ('Themed', 'Develop a theme/style for the document and design the document based on the theme'), ('Infographics', 'Change layouts to high-end infographics by adding vectors/pictograms'), ('Complex animations', 'Use high-end complex animations to represent the data')], max_length=128),
        ),
    ]
