# Generated by Django 3.1.2 on 2020-11-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20201108_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpointquote',
            name='quote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
