# Generated by Django 3.1.2 on 2020-11-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_powerpointquote_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerpointquote',
            name='quote',
        ),
    ]
