# Generated by Django 3.1.2 on 2020-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20201109_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpointproject',
            name='quote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
