# Generated by Django 3.1.2 on 2020-11-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_auto_20201110_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpointproject',
            name='your_full_name',
            field=models.CharField(default='Full Name', max_length=300),
        ),
    ]
