# Generated by Django 3.1.2 on 2020-11-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_powerpointproject_your_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpointproject',
            name='your_full_name',
            field=models.CharField(max_length=300),
        ),
    ]
