# Generated by Django 3.1.2 on 2020-11-20 02:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_auto_20201110_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpointproject',
            name='requirements',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Check for alignment issues, fix fonts and font sizes'), (1, 'Change text/table to other layouts to represent better'), (2, 'Use appropriate cover image and divider image'), (3, 'Use appropriate images and icons/pictograms'), (4, 'Add basic animations/transitions'), (5, 'Convert to an interactive PDF'), (6, 'Develop a theme/style for the document and design the document based on the theme'), (7, 'Change layouts to high-end infographics by adding vectors/pictograms'), (8, 'Use high-end complex animations to represent the data')], max_length=17),
        ),
    ]
