# Generated by Django 3.1.2 on 2020-11-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201102_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='content',
        ),
    ]
