# Generated by Django 3.1.2 on 2020-11-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20201009_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('thumb_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_one_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_two_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_three_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
