# Generated by Django 3.1.2 on 2020-11-15 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='date',
        ),
    ]
